# ----
# Site

title: NetAngel
url: "https://www.netangel.com"
baseurl: "/help"
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /help/netangel-logo-sm.png # TODO
description: >-
  Help Center. New to NetAngel? Learn about NetAngel and how our web filter works.
  Running into a problem? Try searching our help documents and knowledge
  base articles. Find tutorials, articles, videos, walkthroughs,
  features, and more.
author:
  name: NetAngel
  email: info@netangel.com
  twitter: netangelfilter
social:
  name: NetAngel
  links:
    - https://www.facebook.com/NetAngelFilter
    - https://twitter.com/netangelfilter
    - https://plus.google.com/+NetangelFilter
    - https://www.linkedin.com/company/netangel
    - https://www.youtube.com/c/NetAngelFilter
    - https://www.instagram.com/netangelfilter

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon  # TODO

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

# TODO
types:
  - Document
  - Video

_comments:
